package cmd

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/sigcomply/sigcomply-cli/internal/frameworks"
	"github.com/sigcomply/sigcomply-cli/internal/orchestrator"
)

// defaultFramework is the framework selected when neither a flag nor
// $SIGCOMPLY_FRAMEWORK is set. Defined here (production) so init.go and
// evidence.go share one literal.
const defaultFramework = "soc2"

type initFlags struct {
	framework string
	out       string
	force     bool
}

func newInitCmd() *cobra.Command {
	var flags initFlags
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Scaffold a starter .sigcomply.yaml with sensible defaults",
		Long: "`sigcomply init` writes a ready-to-edit .sigcomply.yaml for the chosen\n" +
			"framework. The generated config runs out of the box: the vault defaults\n" +
			"to a local folder and policies auto-bind to whatever sources you list, so\n" +
			"no bindings: block is needed to get started. Commented sections show how\n" +
			"to add sources, narrow bindings, set cadences, declare exceptions, and\n" +
			"enable cloud submission as you grow.\n",
		RunE: func(cmd *cobra.Command, _ []string) error {
			return runInit(cmd.OutOrStdout(), flags)
		},
	}
	cmd.Flags().StringVarP(&flags.framework, "framework", "f", "", "Framework to scaffold for: soc2 | iso27001 (defaults to $SIGCOMPLY_FRAMEWORK, else soc2)")
	cmd.Flags().StringVarP(&flags.out, "out", "o", ".sigcomply.yaml", "Path to write the config to")
	cmd.Flags().BoolVar(&flags.force, "force", false, "Overwrite an existing config file (default: refuse)")
	return cmd
}

func runInit(stdout io.Writer, flags initFlags) error {
	fw := resolveInitFramework(flags.framework)
	if _, ok := frameworks.Lookup(fw); !ok {
		return &exitCodeError{code: orchestrator.ExitConfig,
			err: fmt.Errorf("init: framework %q not supported (registered: %v)", fw, frameworks.IDs())}
	}

	if !flags.force {
		if _, err := os.Stat(flags.out); err == nil {
			return &exitCodeError{code: orchestrator.ExitConfig,
				err: fmt.Errorf("init: refusing to overwrite existing file %q (re-run with --force to override)", flags.out)}
		} else if !os.IsNotExist(err) {
			return &exitCodeError{code: orchestrator.ExitExecution, err: fmt.Errorf("init: stat %q: %w", flags.out, err)}
		}
	}

	if dir := filepath.Dir(flags.out); dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o750); err != nil {
			return &exitCodeError{code: orchestrator.ExitExecution, err: fmt.Errorf("init: mkdir %q: %w", dir, err)}
		}
	}
	if err := os.WriteFile(flags.out, []byte(starterConfig(fw)), 0o600); err != nil {
		return &exitCodeError{code: orchestrator.ExitExecution, err: fmt.Errorf("init: write %q: %w", flags.out, err)}
	}

	const nextSteps = "Next steps:\n" +
		"  1. Edit sources: to list the providers you use; credentials come from the\n" +
		"     environment (AWS_* / GITHUB_TOKEN / GCP ADC / OKTA_API_TOKEN).\n" +
		"  2. Run `sigcomply check` locally to see which controls evaluate.\n" +
		"  3. Run `sigcomply init-ci --ci github` (or gitlab) to scaffold CI workflows."
	_, _ = fmt.Fprintf(stdout, "sigcomply init: wrote %s (framework=%s)\n\n", flags.out, fw) //nolint:errcheck // status output
	_, _ = fmt.Fprintln(stdout, nextSteps)                                                   //nolint:errcheck // status output
	return nil
}

// resolveInitFramework mirrors the rest of the CLI: explicit flag wins,
// then $SIGCOMPLY_FRAMEWORK, then the soc2 default.
func resolveInitFramework(flag string) string {
	if flag != "" {
		return flag
	}
	if env := os.Getenv("SIGCOMPLY_FRAMEWORK"); env != "" {
		return env
	}
	return defaultFramework
}

// starterConfig returns the scaffolded .sigcomply.yaml body for fw. It is
// deliberately heavy on comments — the file is the customer's first
// contact with the config surface, and every optional section is shown
// (commented) so growth never requires hunting through docs. The active
// content must parse and validate (see init_test.go).
func starterConfig(fw string) string {
	return `# .sigcomply.yaml — generated by ` + "`sigcomply init`" + `.
# Full reference: docs/configuration.md
schema_version: project.v1

# Compliance framework to evaluate. Shipped: soc2, iso27001.
framework: ` + fw + `

# ---------------------------------------------------------------------------
# Evidence sources
# ---------------------------------------------------------------------------
# Providers SigComply pulls evidence from. Credentials come from the ambient
# environment (AWS_* / GITHUB_TOKEN / GCP ADC / OKTA_API_TOKEN) — never this
# file. Policies AUTO-BIND to any configured source that emits the evidence
# type they need, so you do NOT need a bindings: block to get started. Replace
# aws.iam below with the sources you actually use.
sources:
  aws.iam:
    region: us-east-1
  # aws.s3: {}
  # aws.cloudtrail: {}
  # github:
  #   org: your-org
  # okta:
  #   org_url: https://your-org.okta.com

  # Manual evidence (a project-level singleton). Many ` + fw + ` controls need
  # documents an API can't produce — access reviews, signed NDAs, security-
  # training certificates, risk-acceptance declarations. Without this source
  # every such control errors out ("source manual.pdf not registered"); with
  # it they simply report fail ("evidence not found") until you upload. Drop
  # the files (PDF/JPEG/PNG/GIF/TIFF/WebP/BMP) into
  #     ./evidence/manual/<evidence_catalog_id>/<period_id>/
  # List the catalog IDs with ` + "`sigcomply evidence catalog -f " + fw + "`" + `. The optional
  # Evidence SPA renders only the declaration/checklist entries; export
  # certificates and HR reports are produced outside it. For production,
  # switch backend to s3 / gcs / azure_blob (one bucket per project).
  manual.pdf:
    backend: local
    path: ./evidence

# ---------------------------------------------------------------------------
# Vault — where signed evidence is stored (it never leaves your environment)
# ---------------------------------------------------------------------------
# Omit this whole block to use a local folder. For production switch to
# s3 / gcs / azure_blob, and make the bucket write-once / versioned for real
# tamper-resistance (S3 Object Lock, GCS Bucket Lock, Azure immutable storage).
vault:
  backend: local
  path: ./.sigcomply/vault
  # backend: s3
  # bucket: my-evidence-bucket
  # region: us-east-1
  # prefix: sigcomply/

# ---------------------------------------------------------------------------
# Per-policy customization (uncomment as needed)
# ---------------------------------------------------------------------------
# Everything about one policy lives under policies:<policy-id>. Each field is
# optional; omit the whole block to take framework defaults + auto-binding.
# policies:
#   <policy-id>:
#     # Narrow to specific sources (overrides auto-binding) — only needed when
#     # several sources emit the same evidence type and you want one:
#     bindings:
#       <slot>: [okta]
#     # Tune a policy parameter (e.g. a threshold):
#     parameters:
#       max_age_days: 60
#     # Override the cadence
#     # (continuous|hourly|daily|weekly|monthly|quarterly|annual or every:<dur>):
#     cadence: weekly
#     # Run this policy from manual PDF evidence instead of an API:
#     evidence_mode: manual
#     catalog_entry: <catalog-id>
#     # Declare scoped waivers / not-applicable with an audit trail:
#     exceptions:
#       - state: waived          # waived | na
#         reason: "Compensating control in place"
#         approved_by: security@example.com
#         approved_at: 2026-01-15
#         # scope: { resource_id: "..." }   # omit to waive the whole policy
#
# ---------------------------------------------------------------------------
# Control-level decisions (uncomment as needed)
# ---------------------------------------------------------------------------
# Mark a whole control not-applicable (cascades na to all its policies) — e.g.
# physical-security controls for a cloud-only company:
# controls:
#   <control-id>:
#     applicability: not_applicable
#     reason: "Inherited from cloud provider; SOC 2 report on file."
#     approved_by: ciso@example.com
#
# Submit aggregated counts to SigComply Cloud (paid tier; OIDC in CI):
# cloud:
#   base_url: https://api.sigcomply.com
`
}
