package manual

// EvidencePDFFilename is the strict, fixed filename of the user-supplied PDF
// for every manual evidence entry. The CLI looks for this exact name (no
// globbing, no case variants) under {framework}/{evidence_id}/{period}/.
//
// The user uploads the PDF directly to this path — the CLI doesn't care how
// it was produced (scanned, exported from a third-party tool, generated by
// the optional Evidence SPA helper). This same filename is mirrored into
// per-policy result folders under manual_attachments/{evidence_id}/evidence.pdf.
const EvidencePDFFilename = "evidence.pdf"
