package iso27001

import (
	"strings"
	"testing"

	"github.com/sigcomply/sigcomply-cli/internal/core"
	"github.com/sigcomply/sigcomply-cli/internal/manualcatalog"
)

// clauseControlIDs returns the management-system controls by ID.
func clauseControlIDs(t *testing.T) map[string]core.Control {
	t.Helper()
	out := map[string]core.Control{}
	for _, c := range Controls() {
		if c.IsManagementSystem() {
			out[c.ID] = c
		}
	}
	return out
}

// TestISMSClauses_CoverMandatoryDocumentedInformation pins the set: the
// documented information ISO 27001:2022 requires of the management
// system, plus the three records (C.4.1-4.2, C.5.3, C.7.5) every
// certification audit asks for without the standard strictly mandating
// a document. A Stage 1 audit is a review of these. Dropping one
// silently would restore the gap this framework shipped with.
func TestISMSClauses_CoverMandatoryDocumentedInformation(t *testing.T) {
	want := []string{
		"C.4.1-4.2", "C.4.3", // context, interested parties, ISMS scope
		"C.5.2", "C.5.3", // policy, roles and authorities
		"C.6.1.2", "C.6.1.3", "C.6.2", // risk assessment/treatment process, objectives
		"C.7.2", "C.7.5", // competence, documented information
		"C.8.1", "C.8.2", "C.8.3", // operational planning, assessment and treatment results
		"C.9.1", "C.9.2", "C.9.3", // monitoring, internal audit, management review
		"C.10.2", // nonconformity and corrective action
	}
	got := clauseControlIDs(t)
	for _, id := range want {
		if _, ok := got[id]; !ok {
			t.Errorf("clause %q is missing from the control catalog", id)
		}
	}
	if len(got) != len(want) {
		t.Errorf("got %d management-system controls, want %d", len(got), len(want))
	}
}

// TestISMSClauses_AreNotAnnexA guards the namespace. Clause 5.2 (the
// information security policy) and Annex A 5.2 (information security
// roles) are different requirements; an ID collision would silently
// merge them.
func TestISMSClauses_AreNotAnnexA(t *testing.T) {
	annex := map[string]struct{}{}
	for _, c := range AnnexAControls() {
		if c.IsManagementSystem() {
			t.Errorf("AnnexAControls returned management-system control %q", c.ID)
		}
		if !strings.HasPrefix(c.ID, "A.") {
			t.Errorf("Annex A control %q does not carry the A. prefix", c.ID)
		}
		annex[c.ID] = struct{}{}
	}
	for id := range clauseControlIDs(t) {
		if !strings.HasPrefix(id, "C.") {
			t.Errorf("clause control %q does not carry the C. prefix", id)
		}
		if _, clash := annex[id]; clash {
			t.Errorf("clause control %q collides with an Annex A control", id)
		}
	}
}

// TestISMSClauses_AreManualDocumentUploads pins the deliberate choice.
// These are documents an auditor reads, not attestations a user clicks
// through: rendering them as Evidence SPA forms would reproduce the
// overclaim the clause set exists to retire.
func TestISMSClauses_AreManualDocumentUploads(t *testing.T) {
	clauses := clauseControlIDs(t)
	entries := ManualCatalogExport().Entries
	byID := map[string]manualcatalog.Entry{}
	for _, e := range entries {
		byID[e.ID] = e
	}

	seen := 0
	for _, p := range Policies() {
		if _, ok := clauses[core.PrimaryControlID(p.Controls)]; !ok {
			continue
		}
		seen++
		if p.EvidenceMode != core.EvidenceModeManual {
			t.Errorf("policy %q: evidence mode %q, want manual", p.ID, p.EvidenceMode)
		}
		if p.Cadence != "annual" {
			t.Errorf("policy %q: cadence %q, want annual — these are yearly management-cycle records", p.ID, p.Cadence)
		}
		if !strings.HasPrefix(p.ID, "iso27001.clause.") {
			t.Errorf("policy %q: want an iso27001.clause. prefix so it cannot be read as an Annex A policy", p.ID)
		}
		e, ok := byID[p.CatalogEntry]
		if !ok {
			t.Errorf("policy %q: no catalog entry %q", p.ID, p.CatalogEntry)
			continue
		}
		if e.Type != manualcatalog.TypeDocumentUpload {
			t.Errorf("catalog entry %q: type %q, want document_upload", e.ID, e.Type)
		}
	}
	if seen != len(clauses) {
		t.Errorf("%d clause policies for %d clause controls — want one each", seen, len(clauses))
	}
}

// TestISMSClauses_SoAIsGeneratedNotUploaded: the Statement of
// Applicability is the one piece of ISO's mandatory documented
// information SigComply produces rather than collects. Asking for it as
// a manual upload as well would be asking the customer to hand back
// what the tool just generated.
func TestISMSClauses_SoAIsGeneratedNotUploaded(t *testing.T) {
	for _, e := range ManualCatalogExport().Entries {
		if strings.Contains(e.ID, "statement_of_applicability") || e.ID == "soa" {
			t.Errorf("catalog entry %q asks for an uploaded SoA; it is generated by report --view soa", e.ID)
		}
	}
}
