package identitycenter

import (
	"encoding/json"
	"testing"
	"time"

	"github.com/aws/aws-sdk-go-v2/service/identitystore"
	"github.com/aws/aws-sdk-go-v2/service/ssoadmin"

	"github.com/sigcomply/sigcomply-cli/internal/core"
	"github.com/sigcomply/sigcomply-cli/internal/sources/aws/awstest"
	"github.com/sigcomply/sigcomply-cli/internal/sources/sourcetest"
)

// identitycenter_conformance_test.go: aws.identity_center L2.
//
// IMPORTANT — the cassette this replays was NOT recorded against a live AWS
// IAM Identity Center tenant (SigComply has none). Its request side is real
// (generated by the aws-sdk-go-v2 serializers, which are themselves generated
// from the published Smithy models); its response bodies are transcribed from
// those models' User / InstanceMetadata shapes. See the provenance header in
// testdata/cassettes/identity_store_users.yaml. Until it is re-recorded
// against a real instance this is a SHAPE test, not a contract test — a field
// AWS populates differently in practice would not be caught here.

const (
	userAda  = "90677c50-e0f1-70ab-7e94-1a2b3c4d5e6f"
	userDana = "b0e7fc40-a021-7033-1b55-6f7e8d9c0a1b"
	userNoML = "c1f81a90-30b1-7093-4c66-7a8b9c0d1e2f"

	// The two other cassette users. The first user's attributes are the
	// package-wide test* consts in identitycenter_test.go.
	testUserNameDana  = "example-user-2"
	testUserNameNoML  = "example-user-3"
	testDisplayDana   = "Dana Example"
	testUserEmailDana = "user-d4e5f6@example.com"
)

// fixedNow is the injected clock: a plugin stamping time.Now() would trip the
// harness's determinism check.
var fixedNow = time.Date(2026, 9, 19, 0, 0, 0, 0, time.UTC)

// newCassettePlugin builds the plugin over the replayed cassette with no
// identity_store_id configured, so every run also exercises the lazy
// sso-admin:ListInstances discovery path.
func newCassettePlugin(t *testing.T) core.SourcePlugin {
	t.Helper()
	cfg := awstest.ReplayConfig(t, "testdata/cassettes/identity_store_users")
	return New(Options{
		API: &awsAPI{
			store: identitystore.NewFromConfig(cfg),
			admin: ssoadmin.NewFromConfig(cfg),
		},
		Region: awstest.Region,
		Now:    func() time.Time { return fixedNow },
	})
}

// assertDirectoryUserEnvelope checks the record metadata every
// directory_user record must carry, whichever user it describes.
func assertDirectoryUserEnvelope(t *testing.T, r *core.EvidenceRecord, p *userPayload) {
	t.Helper()
	if r.SourceID != SourceID {
		t.Errorf("record %s SourceID = %q, want %q", r.ID, r.SourceID, SourceID)
	}
	if r.Scope == nil || r.Scope.Account != testStoreID || r.Scope.Region != awstest.Region {
		t.Errorf("record %s Scope = %+v, want the discovered store id + region", r.ID, r.Scope)
	}
	if p.MFAEnabled {
		t.Errorf("record %s mfa_enabled = true; Identity Center cannot prove MFA, so it must stay false", r.ID)
	}
}

// assertCreatedAt compares an optional created_at against its expectation,
// where a nil want means "the directory published none".
func assertCreatedAt(t *testing.T, got, want *time.Time) {
	t.Helper()
	switch {
	case want == nil && got != nil:
		t.Errorf("created_at = %v, want none", got)
	case want != nil && got == nil:
		t.Errorf("created_at = nil, want %v", want)
	case want != nil && got != nil && !got.Equal(*want):
		t.Errorf("created_at = %v, want %v", got, want)
	}
}

// TestIdentityCenterDirectoryUserConformance runs the shared harness over the
// directory_user (v1) half of the plugin's output.
func TestIdentityCenterDirectoryUserConformance(t *testing.T) {
	recs := sourcetest.RunConformance(t, &sourcetest.Options{
		Plugin:        newCassettePlugin(t),
		Request:       core.SlotRequest{AcceptedTypes: []string{EvidenceTypeDirectoryUser}},
		EvidenceTypes: sourcetest.BuiltinEvidenceTypes(t),
		OptionalFields: []string{
			// No public Identity Center API exposes these at all.
			"directory_user.mfa_factor_count",
			"directory_user.is_admin",           // needs a permission-set traversal
			"directory_user.is_service_account", // the identity store has no such flag
			"directory_user.is_external",        // membership is not modeled
			"directory_user.last_login_at",      // no sign-in activity in the identity store
			// Per-user optional attributes: the third fixture user carries
			// neither, which is the shape a SCIM-synced store often has.
			"directory_user.email",
			"directory_user.created_at",
		},
	})
	if len(recs) != 3 {
		t.Fatalf("directory_user records = %d, want 3", len(recs))
	}

	byID := map[string]core.EvidenceRecord{}
	payloads := map[string]userPayload{}
	for i := range recs {
		r := &recs[i]
		p := payloadOf[userPayload](t, r)
		byID[r.ID] = *r
		payloads[r.ID] = p
		assertDirectoryUserEnvelope(t, r, &p)
	}

	adaCreated := time.Date(2024, 6, 13, 16, 0, 0, 0, time.UTC)
	danaCreated := time.Date(2024, 7, 9, 0, 0, 0, 0, time.UTC)
	for _, c := range []struct {
		name        string
		id          string
		username    string
		displayName string
		email       string
		identityKey string
		isActive    bool
		createdAt   *time.Time
	}{
		// IdentityKey is the lowercased email and the linker reads
		// payload.email, so the two must always agree.
		{"every attribute present", userAda, testUserName, testDisplayName, testUserEmail, testUserEmail, true, &adaCreated},
		// UserStatus DISABLED, and no DisplayName attribute: the display
		// name is composed from Name.GivenName + Name.FamilyName.
		{"disabled with a composed display name", userDana, testUserNameDana, testDisplayDana, testUserEmailDana, testUserEmailDana, false, &danaCreated},
		// No email at all: the display name falls back to the user name
		// and the identity key is empty rather than invented.
		{"no email, display name falls back", userNoML, testUserNameNoML, testUserNameNoML, "", "", true, nil},
	} {
		t.Run(c.name, func(t *testing.T) {
			p := payloads[c.id]
			for _, f := range []struct {
				field string
				got   any
				want  any
			}{
				{"username", p.Username, c.username},
				{"display_name", p.DisplayName, c.displayName},
				{fieldEmail, p.Email, c.email},
				{"is_active", p.IsActive, c.isActive},
				{"IdentityKey", byID[c.id].IdentityKey, c.identityKey},
			} {
				if f.got != f.want {
					t.Errorf("%s = %v, want %v", f.field, f.got, f.want)
				}
			}
			assertCreatedAt(t, p.CreatedAt, c.createdAt)
		})
	}

	// The third user has no email and no CreatedAt: both keys must be ABSENT,
	// never emitted as "" or year 0001 (the null trap).
	noML := byID[userNoML]
	assertPayloadOmits(t, noML.Payload, fieldEmail, "created_at", "is_admin", "last_login_at")
}

// TestIdentityCenterRosterConformance runs the shared harness over the
// roster_entry half. roster_entry is additionalProperties:false with
// minLength:1 on every optional string, so an empty value must be omitted
// rather than emitted.
func TestIdentityCenterRosterConformance(t *testing.T) {
	recs := sourcetest.RunConformance(t, &sourcetest.Options{
		Plugin:        newCassettePlugin(t),
		Request:       core.SlotRequest{AcceptedTypes: []string{EvidenceTypeRosterEntry}},
		EvidenceTypes: sourcetest.BuiltinEvidenceTypes(t),
		OptionalFields: []string{
			"roster_entry.employee_id",        // only in the aws:identitystore:enterprise extension
			"roster_entry.is_service_account", // the identity store has no such flag
			"roster_entry.employee_type",      // SCIM userType is optional per user
			"roster_entry.email",              // a user need not have an address
		},
	})
	if len(recs) != 3 {
		t.Fatalf("roster_entry records = %d, want 3", len(recs))
	}
	want := map[string]struct{ status, sourceStatus, email, employeeType string }{
		userAda:  {rosterActive, statusEnabled, testUserEmail, testEmployeeType},
		userDana: {rosterInactive, statusDisabled, testUserEmailDana, ""},
		userNoML: {rosterActive, statusEnabled, "", ""},
	}
	for _, r := range recs {
		var p rosterPayload
		if err := json.Unmarshal(r.Payload, &p); err != nil {
			t.Fatal(err)
		}
		w, ok := want[r.ID]
		if !ok {
			t.Fatalf("unexpected roster record %q", r.ID)
		}
		if p.Status != w.status || p.SourceStatus != w.sourceStatus || p.Email != w.email || p.EmployeeType != w.employeeType {
			t.Errorf("roster %s = %+v, want %+v", r.ID, p, w)
		}
	}
}

// TestIdentityCenterBothTypesConformance proves one listing serves both types
// and that the shared record ID does not break the sort contract.
func TestIdentityCenterBothTypesConformance(t *testing.T) {
	recs := sourcetest.RunConformance(t, &sourcetest.Options{
		Plugin:        newCassettePlugin(t),
		EvidenceTypes: sourcetest.BuiltinEvidenceTypes(t),
		OptionalFields: []string{
			"directory_user.mfa_factor_count", "directory_user.is_admin",
			"directory_user.is_service_account", "directory_user.is_external",
			"directory_user.last_login_at", "directory_user.email", "directory_user.created_at",
			"roster_entry.employee_id", "roster_entry.is_service_account",
			"roster_entry.employee_type", "roster_entry.email",
		},
	})
	if len(recs) != 6 {
		t.Fatalf("records = %d, want 6 (3 users x 2 types)", len(recs))
	}
}
